### ISSUE TITLE
Failed to load the switch-header-source package

### ISSUE THREAD

**Issue by bguil** [dschwen/switch-header-source#17]
[Enter steps to reproduce:]

The error happends when Atom starts.

The error appears after update to 1.0.0.
It was suggested to update Atom to 1.23.1. I did so and the error is still their.

By the way, thanks for this usefull package! I hope it will be fixed soon!

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [switch-header-source](https://github.com/dschwen/switch-header-source) package 1.0.0

### Stack Trace

Failed to load the switch-header-source package

```
At Cannot find module 'fuzzy-finder/lib/path-loader'

Error: Cannot find module 'fuzzy-finder/lib/path-loader'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/switch-header-source/lib/switch-header-source.coffee:5:15)
    at /packages/switch-header-source/lib/switch-header-source.coffee:1:1)
    at /packages/switch-header-source/lib/switch-header-source.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:34
```

### Commands

```
```

### Non-Core Packages

```
bibtex-snippets 0.1.0 
build 0.69.0 
busy 0.7.0 
busy-signal 1.4.3 
grammar-live-reload 1.0.6 
highlight-cursor-line 0.2.4 
intentions 1.1.5 
language-conll undefined 
language-grew undefined 
language-latex 1.1.1 
language-ocaml 1.9.5 
latex 0.49.0 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
ocaml-merlin 0.14.4 
split-diff 1.5.1 
switch-header-source 1.0.0 
```

**Comment by dschwen** [comment]
Yuck, I just released that. Let me look into it.

**Comment by dschwen** [comment]
Ok, I unpublished the '1.*' versions. Could you check if '0.24.4' works for you?

**Comment by dschwen** [comment]
Tested on Mac and Linux. The bug reported here is fixed. If there is still a problem please open a new issue. Thanks!
